### ISSUE TITLE
Force reroll command is unregistered for me

### ISSUE THREAD

**Issue by Tylerguns12** [GruffCassquatch/RerollBurntBuildings#4]
in coastal highway i have the option enabled but when i go to the interloper commands i type force_reroll_burntbuildings then where i want to reroll but the commands dont work- any ideas?

**Comment by GruffCassquatch** [comment]
Hi, I am not currently modding as I am focused on caring for my husband while he has a long-term health issue. This mod was updated by another modder, but I don't believe they're intending to continue to update it. It is what it is for now.
